platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

plugin 'cocoapods-art', :sources => [
  'foursquare'
]
target 'RNPilgrimSample' do
  use_frameworks!
  
  pod 'pilgrim-sdk', '~> 1.3.2'
end
